### ISSUE TITLE
DynamicDNSUPdater TLS 1.2

### ISSUE THREAD

**Issue by ghislainborremans** [Nesos-ita/DynamicDnsUpdater#4]
Hello 
I installed it on W10 but it does not start ( nothing in log neither ) Can you help 
Best regards 
Ghislain

**Comment by CornelisJ** [comment]
When downloading the Compiled Binary with your web browser, do NOT save DynamicDnsUpdater.exe by rightclicking and using "Save link as ...".
Instead, click on DynamicDnsUpdater.exe and then in the next screen click the Download button to download the binary. That worked for me.

**Comment by Nesos-ita** [comment]
What do you mean with "doesn't start"?
- nothing happens if you double click on the program
- the program opens, you fill the data, click ok but it doesn't become green and stay stopped

If it doesn't open, do you have the .NET framewrok 4.8 installed?
with the last version i had to use a newer net framework, here is a download link: http://go.microsoft.com/fwlink/?LinkId=2085155

> When downloading the Compiled Binary with your web browser, do NOT save DynamicDnsUpdater.exe by rightclicking and using "Save link as ...".

left click from the documentation should work "1 - Download the program under [Compiled Binary/DynamicDnsUpdater.exe](https://github.com/Nesos-ita/DynamicDnsUpdater/raw/master/Compiled%20Binary/DynamicDnsUpdater.exe)"
if the saved file has an icon you probably downloaded it correctly.
if you instead click on the top in the file list there is an extra page that ask for confirmation, so right click sould be avoided

**Comment by ghislainborremans** [comment]
installed .net 4.8 and it works. thanks
