### ISSUE TITLE
IP Update Exception

### ISSUE THREAD

**Issue by CornelisJ** [Nesos-ita/DynamicDnsUpdater#6]
I am using DynamicDnsUpdater in combination with the deSEC DynDNS service for sending my external IP address to deSEC.
Today I found that getting my external IP address with DynamicDnsUpdater does not seem to work anymore.

After starting the DynamicDnsUpdater GUI, the following error is reported in the status line at the bottom of the GUI:
`Status: Update result: UnknownError`

Excerpt from the log file:
```
24-2-2022 15:35:16 - Settings read OK
24-2-2022 15:35:17 - Version: 1.2.0.37078
24-2-2022 15:35:17 - GUI mode
24-2-2022 15:35:21 - DDNS upadater running
24-2-2022 15:35:23 - UPDATE Exception, unknown status: Request aborted: Unable to create secure SSL/TLS channel.
24-2-2022 15:35:23 - Updating DNS: UnknownError
24-2-2022 15:35:24 - DDNS upadater stopped
```
When I click "Manually update now your ddns", the log file says:
```
24-2-2022 15:40:35 - UPDATE Exception, unknown status: Request aborted: Unable to create secure SSL/TLS channel.
24-2-2022 15:40:35 - Manually updating DNS: UnknownError
```
When I click "Get Current IP", nothing is added to the log file, but the status line at the bottom of the GUI says:
`Status: Error while getting current ip`

So it seems that for some reason DynamicDnsUpdater cannot resolve my external IP address anymore.
Are there other people that experience the same problem? Any suggestions to resolve this problem?

EDIT: When configuring the ddclient on Linux, URL https://checkipv4.dedyn.io is used to get the external IP address, see [here](https://desec.readthedocs.io/en/latest/dyndns/configure.html#manual-configuration-other-systems). Maybe it is an idea to add an extra field to DynamicDnsUpdater for entering an URL that returns the external IP address?

**Comment by Nesos-ita** [comment]
i tried to click get current ip on my computer (windows 10) and it works normally.  
currently the url used to retrive current ip is: [https://checkip.dedyn.io ](https://checkip.dedyn.io)  
the problem is that in your case is not possible to open an https connection to that website but i'm not sure what could be causing this...  
the first idea that comes to my mind is wrong pc clock but reading the log that is not the case, clock is correct.  
Does that website opens from browser? seems a certificate problem and a browser might give you more details on what exactly is going on.  
is the computer updated? maybe there is some intermediate/root certificate expired or missing.  
Another option could be some program blocking the connection, have you changed antivirus recently? some of them try to intercept tls connections using custom certificates.

**Comment by CornelisJ** [comment]
Thanks for your reply. FYI, the information that I gave in my first post was not fully correct. I have now corrected this.
When I click "Get Current IP", nothing is added to the log file, but the status line at the bottom of the GUI says:
Status: Error while getting current ip

When I open https://checkip.dedyn.io or https://checkipv4.dedyn.io in a browser (Microsoft Edge Chromium) on my server that runs DynamicDnsUpdater, then the correct external IP address is shown.

The problem could be that my 12 year old server that gives the IP Update Exception still runs **Windows 7**....
When I run DynamicDnsUpdater on my main PC that runs Windows 10, the program runs without problem!
Maybe deSEC somehow checks the OS of the host that does the IP query via https://checkip.dedyn.io ,and does not respond when  the OS is Windows 7? I am just guessing now. In the past DDU ran without problem on this server / Windows 7.

Anyway, since Windows 7 is not supported anymore by Microsoft, I am now migrating my server to Linux. And I have already seen that the ddclient on Linux works OK in combination with deSEC.

**Comment by Nesos-ita** [comment]
i suspect that the problem is some missing update on the windows 7 pc, probably the support for tls1.2 or some root certificate expired, try to check if it's windows 7 SP1 or if it's the older windows 7 without service pack.  
consider using [wsus offline](https://download.wsusoffline.net/wsusoffline119.zip) to update windows and/or the root ca certificates, it should be easy and automated with few clicks, note that you need version 11.9 (the linked one) which support windows 7 upgrading, newer versions dropped the support.  
i tested the program on a fully updated win7 and it works

**Comment by CornelisJ** [comment]
Excuses me for my late reply. The Windows 7 PC/server was using Windows 7 SP1 with the latest updates. I was running an IIS 7.5 https webserver on this system with TLS1.2 encryption, using an Let's Encrypt certificate, for remote access to files on this server. I don't know for sure however if root certificates were still valid.

In the mean time I have installed Linux Mint 20.3 XFCE on this server, including https web server. I am now using ddclient in combination with the deSEC DynDNS and this is working fine. 

Since DynamicDnsUpdater is working fine on your Windows 7 PC, and because Windows 7 is not installed anymore on my server, I am closing this issue. Thanks for your hints, they may still be useful for other users of your program.
