### ISSUE TITLE
Had to turn off ipv6 to get it to work.

### ISSUE THREAD

**Issue by a10k** [Nesos-ita/DynamicDnsUpdater#8]
I noticed on desec.io that the updated ip is in ipv6 format, and it doesn't seem to work as expected, after turning ipv6 off from the network settings, everything seems to work fine.

**Comment by Nesos-ita** [comment]
i missed the issue, sorry for the delay.
according to [their documentation](https://desec.readthedocs.io/en/latest/dyndns/configure.html) there is a different url for IPv6: `update6.dedyn.io`.  
I have not implemented a way to explicitly chose between updating IPv4, IPv6 or both since i have only IPv4 and i don't plan to implement it in the near future.  
Thanks for the information.
